-- AlterTable
ALTER TABLE "SkuSnapshot" ADD COLUMN     "awdInbound" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "awdOnhand" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "units10d" INTEGER NOT NULL DEFAULT 0;
